# Generated by Django 3.2.4 on 2024-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
